apiVersion: v1
kind: Service
metadata: 
  name: {{ template "bigchaindb.fullname" . }}-svc
spec:    
  ports:
  - name: api
    port: 9984
    targetPort: 9984
  - name: websocket
    port: 9985
    targetPort: 9985
  - name: mongodb
    port: 27017
    targetPort: 27017
  - name: tendermint
    port: 26657
    targetPort: 26657
  selector: 
    app: {{ template "bigchaindb.name" . }}
  type: NodePort