apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "bigchaindb.fullname" . }}-ss
spec:
  serviceName: {{ template "bigchaindb.name" . }}
  selector:
    matchLabels:
      app: {{ template "bigchaindb.name" . }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "bigchaindb.name" . }}
    spec:
      containers:
      - name: {{ template "bigchaindb.name" . }}
        image: {{ .Values.image}}
        ports:
        - name: api
          containerPort: 9984
        - name: websocket
          containerPort: 9985
        - name: mongodb
          containerPort: 27017
        - name: tendermint
          containerPort: 26657
        volumeMounts:
        - name: mongo-data-ps
          mountPath: /data/db
        - name: mongo-config-ps
          mountPath: /data/configdb
        - name: tendermint-ps
          mountPath: /tendermint
  volumeClaimTemplates:
  - metadata:
      name: mongo-data-ps
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: mongo-config-ps
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: tendermint-ps
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi